package com.saimon.controle_financeiro.Domain.Enum;

public enum LogTipoEvento {
	LOGIN,
	MOVIMENTACAO_CRIADA,
	MOVIMENTACAO_ATUALIZADA,
	MOVIMENTACAO_DELETADA,
	LISTAR_MOVIMENTACAO,
	USUARIO_CRIADO,
	USUARIO_ATUALIZADO,
	USUARIO_DELETADO

}
